baseURL = "https://bio-formatics.github.io/"
languageCode = "en-us"
title = "Bioinformatics"
theme = "hugo-theme-learn"
publishDir = "docs"

[params]
themeVariant = "devops"
disableSearch = false

[outputs]
home = ["HTML", "RSS", "JSON"]

